# -*- coding: utf-8 -*-
"""exploratory_dataanalysis.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCSkTWBiQGXMBJHD8hHExXvX4pl8RVG6

# exploratory-data-analysis1

Use the "Run" button to execute the code.

#Exploratory Data Analysis

####This file contains application data of more than 600K applications in Google Play store
####It can be useful to analyse popularity of Play Store apps.
####Source of the data is Kaggle.

##Download Data
"""

pip install opendatasets --upgrade --quiet

import opendatasets as od
dataset_url = 'https://www.kaggle.com/datasets/gauthamp10/google-playstore-apps'
od.download('https://www.kaggle.com/datasets/gauthamp10/google-playstore-apps')

dataName = './google-playstore-apps/Google-Playstore.csv'

"""##Data Preparation
#### 1. Load the file using Pandas.
#### 2. Check out some data.
"""

import pandas as pd

df = pd.read_csv(dataName)

df.head()

df.transpose()
df.head()

df = df.drop(labels = ['Maximum Installs','Minimum Installs','Price','Currency','Developer Website','Developer Email', 'Privacy Policy','Minimum Android', 'Developer Id','Scraped Time'],axis = 1)

df.head()

df.columns

df.drop(labels= ['Editors Choice'], axis = 1)

df.set_index('App Name', inplace = True)

df.head()

df.drop(labels = ['App Id'], axis = 1)